services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
      - KBN_PATH_CONF=/usr/share/kibana/config
    entrypoint: ["/usr/share/kibana/bin/kibana", "--allow-root"]
    user: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
