# Configuration for the file indexer

# LucidLink Filespace configuration
lucidlink_filespace:
  enabled: true  # Enable LucidLink integration
  get_direct_links: true  # Set to false to skip generating direct links (faster indexing)
  lucidlink_version: 3  # LucidLink API version (2 or 3)
  port: 9778  # LucidLink API port
  calculate_directory_sizes: true  # Calculate directory sizes (requires additional processing)
  
  # Version-specific settings
  v2_settings:
    # Cache fsentry_ids for faster direct link generation
    enable_fsentry_cache: true
    # Cache TTL in hours
    cache_ttl_hours: 1
    # Maximum concurrent API requests for ID lookup
    max_concurrent_requests: 20
    # Retry settings for API calls
    retry_attempts: 3
    retry_delay_seconds: 1
    
  v3_settings:
    # Maximum concurrent API requests for direct links
    max_concurrent_requests: 4  # API bound, so keep low
    # Retry settings for API calls
    retry_attempts: 5
    retry_delay_seconds: 0.5
    # Batch size for direct link requests
    batch_size: 10000
    # Queue size for async processing
    queue_size: 10000

# =============================================

# Root path to start indexing from (optional, can be provided via --root-path argument)
root_path: ""

# =============================================
# Elasticsearch configuration
# =============================================
elasticsearch:
  host: localhost
  port: 9200
  username: ""  # Leave empty for no authentication
  password: ""  # Leave empty for no authentication
  index_name: filespace # For LucidLink filespaces, app uses filespace-domain for index name
  ssl: false
  
  # Bulk indexing settings
  bulk_size: 50000
  max_retries: 3
  timeout_seconds: 300
  retry_on_timeout: true

# =============================================
# Operation Mode
# =============================================
# Available modes:
# - elasticsearch: Run indexer and send records to Elasticsearch (default)
# - index-only: Run indexer only, do not send records to Elasticsearch
mode: elasticsearch

# =============================================
# Database configuration
# =============================================
database:
  connection:
    url: "duckdb:///data/fs_index.duckdb"
    options:
      memory_limit: "4GB"
      threads: 10
      temp_directory: "./.tmp"
      checkpoint_on_shutdown: true
      compression: "lz4"
      
  # Table-specific settings
  tables:
    direct_links:
      # Vacuum settings
      auto_vacuum: true
      vacuum_threshold: 10000
      # Index settings
      create_indexes: true
      index_types: ["last_updated", "fsentry_id"]

# =============================================
# Performance configuration
# =============================================
performance:
  # Batch sizes for different operations
  batch_sizes:
    scan: 25000
    direct_links: 50000
    elasticsearch: 10000
    
  # Parallel processing settings
  parallel_processing:
    enabled: true
    max_workers: 10  # Number of parallel workers (default: number of CPU cores)
    batch_size: 100000  # Maximum files per batch
    
  # File scanning settings
  scan_chunk_size: 25000  # Size of batches for file scanning
  
  # Progress reporting
  progress_interval_seconds: 5
  show_rate_stats: true
  show_memory_stats: true

# Check and remove database records for files that no longer exist
check_missing_files: false

# Skip patterns for file scanning
skip_patterns:
  # Hidden files and directories
  hidden_files: true
  hidden_dirs: true
  
  # Specific patterns to skip (glob format)
  patterns:
    - '.DS_Store'
    - '.git'
    - '.gitignore'
    - '.svn'
    - '.hg'
    - '.idea'
    - '.vscode'
    - '__pycache__'
    - '*.pyc'
    - '*.pyo'
    - '*.pyd'
    - '*.so'
    - '*.dylib'
    - '*.dll'
    - '*.class'
    - '*.o'
    - '*.dbr'
    - '.lucid_audit'
    - '.Trash*'
    - '.Spotlight*'
    - '.LP_Store*'
    
# =============================================
# Logging configuration
# =============================================
logging:
  # Log level options (from most to least verbose):
  # - "DEBUG": Shows file processing details, API responses, and debug info
  # - "INFO": Shows progress updates, batch processing, and summary stats
  # - "WARNING": Shows when some files in a batch couldn't be processed
  # - "ERROR": Shows only errors that prevent processing
  level: "INFO"
  
  # File logging settings
  file:
    enabled: true
    path: "logs/fs-indexer.log"
    max_size_mb: 10
    backup_count: 5
    
  # Console logging settings
  console:
    enabled: true
    show_timestamps: true
    color: true
    
  # Performance logging
  performance:
    enabled: true
    interval_seconds: 60
    include_memory: true
    include_disk: true